### ISSUE TITLE
Several typos in API documentation

### ISSUE THREAD

**Issue by gamtiq** [florian/xStore#10]
There are the following typos in [API documentation](https://github.com/florian/xStore/blob/master/docs/api-documentation.md):
> This allows *seperate* stores with different prefixes to save values under the same key.

> Use the get method, or its shortcut: *store.)* / session(), to retrieve values.

> *store.'key');* // Or: session('key')

> Call store.all to get all data saved with the *`store.* object:

> This will remove all of the data that was saved with *`store.*:

> This appends a string to a *store. /session`* value:

**Comment by florian** [comment]
Thanks! I've fixed all of them.
The `.` ones are super weird, I probably ran some find/replace text command that didn't work as intentioned.
