### ISSUE TITLE
Removing item from localStorage

### ISSUE THREAD

**Issue by mouse0270** [florian/xStore#11]
Some I am using this to update alerts when users visit the homepage so they have access to them on the sub pages. This is because we are using a custom framework that doesn't really support this functionality.

So every time the user goes to the homepage it will append new alerts to the localstorage, but I would also like to use this time to clean out the old alerts so the localstorage never fills up.

my code looks like this

```javascript
console.log(epsAlerts.all());
$.each(epsAlerts.all(), function(index, alert) {
	if ($('#sw-content-container11 .announcements a[href="#' + index +'"]').length >= 1) {
		$('.z-mystart .dropdown-alerts .dropdown-menu').append('<li>'+alert.content+'</li>');
	}else{
		console.log(index);
		epsAlerts.remove(index);
	}
});
console.log(epsAlerts.all());
```

I get the `console.log(index)` for my third item that has expired and should no longer be displayed. However when calling the second `console.log(epsAlerts.all());` I can still see all three of the alerts.

I am using the latest release (v2.0.3) downloaded today (5/3/2017). Am I using the `.remove` wrong or doing something else wrong? Thank you for any assistance you can provide.

`console.log(index);` = `alert12326032269`

Last `console.log(epsAlerts.all())` returns
```
{
	"alert02325932268": {
		"content": "<div class=\"ui-article-description danger\"><span><p>Due to a facility issue at Central Tech, school has been cancelled today for <strong>Central Tech and Roosevelt students only</strong>. All other schools are in session today (5/26).</p></span></div>",
		"visible": true
	},
	"alert02326032270": {
		"content": "<div class=\"ui-article-description info\"><span><p><strong>Board of School Directors</strong></p><p>Committee of the Whole Meeting starting at 6pm.</p></span></div>",
		"visible": true
	},
	"alert12326032269": {
		"content": "<div class=\"ui-article-description info\"><span><p>Due to a facility issue at Central Tech, school has been cancelled today for<br>Example.com</p></span></div>",
		"visible": true
	}
}
```

**Comment by florian** [comment]
Hey, it looks like you found a bug that snuck in during the last rewrite. The problem was that `remove` was ignoring the store prefix. I just pushed a new version and also added a unit test for this.

Let me know if this also fixes things for you! And sorry for the inconvenience this caused, such a basic bug really shouldn't occur.

**Comment by mouse0270** [comment]
PERFECT!!!

Thank you so much, I was going crazy trying to figure out what I did wrong. It is working exactly as expected.
