### ISSUE TITLE
.get needs prefix to be prefixed to key

### ISSUE THREAD

**Issue by aseemgautam** [florian/xStore#7]
Not sure if this is by design. The sample code on the main page does not uses the prefix to access value.
```
var store = new xStore('prefix:', localStorage);
store.empty();
store.set("userToken" , "some value");
console.log(store.get("userToken")); //undefined
console.log(store.get("prefix:userToken")); //some value
```
https://jsbin.com/rexajaqehu/1/edit?html,js,console

**Comment by florian** [comment]
Whoa, yes that's a bug. The unit tests checked for the wrong thing, so I didn't notice when rewriting the library three weeks ago.

Thanks for reporting it :) I've fixed it and published a new version to NPM.
